### ISSUE TITLE
Blank Option Window in Gnome shell 3.22.0

### ISSUE THREAD

**Issue by sajjadG** [iacopodeenosee/EasyScreenCast#106]
Hi, 
When I open the option window it's blank, shows nothing. I've upgraded my Debian, gnome-shell and the plugins but I still can't see any widget in the option window.

When I use the gnome top panel and press start recording it starts recording but when I press stop recording it doesn't finish the recording and creates a 0 byte file.

I'm using Debian testing with `GNOME Shell 3.22.0` and have the latest `gstreamer` with plugins, but I'm not sure if I have all the requirements (is there any screencasting app I should install? istanbul?)

It seems there's not a 3.22.0 extension in [https://extensions.gnome.org](extensions.gnome.org) yet. so I've added 3.22 to the `metadata.js` just in case. but no difference.

**Comment by iacopodeenosee** [comment]
hi, this extension is not tested on 3.22 yet, you might see some useful information [in the logs](https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs).
if the problem is only in the options window you can launch it from terminal by this command:
`gnome-shell-extension-prefs  EasyScreenCast@iacopodeenosee.gmail.com`
so you have the logs directly into the terminal.
where you downloaded the extension?
 [ ] Gnome shell extension website
 [ ] Last release from git repo
 [ ] Last version from git on master branch repo

**Comment by sajjadG** [comment]
```
$ gnome-shell-extension-prefs EasyScreenCast@iacopodeenosee.gmail.com

(gnome-shell-extension-prefs:6111): Gjs-WARNING **: JS ERROR: Error: No property propagate_natural_width on this GObject GtkScrolledWindow
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/overrides/Gtk.js:107
Application<._buildUI@resource:///org/gnome/shell/extensionPrefs/main.js:156
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Application<._onStartup@resource:///org/gnome/shell/extensionPrefs/main.js:222
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
main@resource:///org/gnome/shell/extensionPrefs/main.js:377
@<main>:1
```

[this](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1456542.html) link is the only related thing I could find by googling. 
I think it's duo to GTK3 api change. Fast changing apis are crazy. 

where you downloaded the extension?
**[ * ] Gnome shell extension website**
[ ] Last release from git repo
[ ] Last version from git on master branch repo
I had this plugin in 3.20 and then I upgraded the system and got gnome-shell 3.22 and the interesting part is that 3.22 was not in metadata.js supported versions but gnome-shell loaded the plugin!!!

**Comment by iacopodeenosee** [comment]
> I had this plugin in 3.20 and then I upgraded the system and got gnome-shell 3.22 and the interesting part is that 3.22 was not in metadata.js supported versions but gnome-shell loaded the plugin!!!

GS 3.22 load any extensions, no longer check on the field **version** of the file metadata.js. 
i think is a bug related at pkg dependence of debian and that has been resolved.
