### ISSUE TITLE
install on debian 64 jessie Error

### ISSUE THREAD

**Issue by derbiccp** [iacopodeenosee/EasyScreenCast#107]
hello error debian 8 jessie how to fix?   please
`Gtk.BuilderError: /home/debweb/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/EasyScreenCast.gtkbuilder: required gtk+ version 3.16, current version is 3.14

Stack trace:
  EasyScreenCastSettingsWidget<._init@/home/debweb/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:98
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  buildPrefsWidget@/home/debweb/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:754
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:96
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1

**Comment by iacopodeenosee** [comment]
> required gtk+ version 3.16, current version is 3.14

you need to install gtk+ version 3.16, otherwise try an older version of ESC, like 0.9.4. thx

**Comment by laykatz** [comment]
Hi I'm having the same issue and as you recommended to install 0.9.4 no longer exist

**Comment by iacopodeenosee** [comment]
try this -> https://drive.google.com/open?id=0B-9Vhm54fr7TZmxraWdZSGc5SU0
it's 0.9.4 version from my backup, i suggest to remove the old directory of ESC before install this. thx

**Comment by laykatz** [comment]
Thank you. @iacopodeenosee
