### ISSUE TITLE
suggestion: allow videos to be saved as gif

### ISSUE THREAD

**Issue by gavinengel** [iacopodeenosee/EasyScreenCast#11]
Here is a suggestion out of left field :-)  I'd love to have the option to save the video as a gif.  Is there any chance of that?

**Comment by iacopodeenosee** [comment]
i'm not a gstreamer expert but i think it's not possible convert the video file into a gif with the shell recorder, below there is the documention that I found about it
http://gstreamer.freedesktop.org/documentation/plugins.html
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-videoconvert.html
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gstreamer-video.html
I'll keep it open until someone confirm this, thx 8y3.

**Comment by gavinengel** [comment]
It would be useful I think.  Perhaps modifying the gstreamer pipeline would be able to do it.  You know, another suggestion could be this:  If you allow a custom shell command to be run on the final recording, we could install conversion packages and add a line into a "Final shell command to be run on the result" in your options.

**Comment by iacopodeenosee** [comment]
"Final shell command to be run on the result" i  think is useful and simple to implement, when i have some free time i'll try to add this function. thx, 8y3

**Comment by gavinengel** [comment]
I appreciate your consideration.
