### ISSUE TITLE
Integrate webcam video 

### ISSUE THREAD

**Issue by davelab6** [iacopodeenosee/EasyScreenCast#15]
Following https://github.com/iacopodeenosee/EasyScreenCast/issues/4 it would be great to support not only sound but also the web cam, like silverbackapp.com - integrating the webcam video into the main videorecording, with adjustable position (default in the right-bottom corner) This should be possible with gstreamer :)

**Comment by joaoherberto** [comment]
This seems like it would add too much overhead... no? I use VLC in minimal mode and select the capture device, (I have two), then set it as always on top and resize the output to your liking. Then when you record the desktop, your capture includes the webcam output. It works really well at 30FPS.

This also allows much more finite control of the video output.

**Comment by davelab6** [comment]
Cool! Maybe add that tip to the readme :)

**Comment by iacopodeenosee** [comment]
is a neat trick that I had not thought, the implementation of the webcam I've finished and I think in this weekend will publish the new version that implement it, test it although at the moment you can not move it from the top left corner and also you can not resize it...
until I finish the job i think that  your solution can still be the most comfortable :)

**Comment by iacopodeenosee** [comment]
https://github.com/iacopodeenosee/EasyScreenCast/commit/f91928035749debd6cab1fb1a94a25019e29e366
