### ISSUE TITLE
Selecting recording area from the menu

### ISSUE THREAD

**Issue by torokati44** [iacopodeenosee/EasyScreenCast#18]
It would be great if one could select the target area of the recording easily at the start of every recording, right from the menu.
Because sometimes I would want to record a window, or an area, or one desktop, and it is rather inconvenient having to always change this in the Options GUI.
So maybe you could add another option to the combobox on the "Screencast area" tab, something like "Selected at every recording", and if it is active, a few extra elements would appear in the menu under the "Start recording" option, one for each possible target selection.
Or maybe these could be there all the time, in a foldable submenu, and the main option would adhere to the selected option in the GUI, but these would always use a specific selection mode.

**Comment by iacopodeenosee** [comment]
I do not think there are problems to implement it, the option GUI part remains unchanged just add a list submenu list that change directly the settings of extension, feel free to contribute if you want. 8y3

**Comment by iacopodeenosee** [comment]
this is a image of the new menu:
![esc_newmenu](https://cloud.githubusercontent.com/assets/4881584/8888927/29039da4-32c3-11e5-9ec3-e02e7b466ba3.jpg)
I will delete the relative part in the UI preferences that I find useless now. 8y3
