### ISSUE TITLE
"Maximum recording duration" setting is useless?

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#26]
Is there a real usecase for this setting? Why would anyone want to artificially limit the length of a recording session? If nobody provided a clear reason for this to exist, I would suggest removing that setting from the preferences (it even has a tooltip in italian that mentions bug 708660, which has been marked as resolved 1.5 years ago)

**Comment by iacopodeenosee** [comment]
you're right, this key setting no longer exists from version 3.10, maybe 3.12, and when the switch is effective only in those versions of GS.
