### ISSUE TITLE
Replace the custom big file chooser widget by a small GTK FileChooserButton

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#27]
In the settings, there is a huge area eaten by a full-fledged file chooser widget.
Instead, it would be better to use https://developer.gnome.org/gtk3/stable/GtkFileChooserButton.html
and to specify the "SELECT_FOLDER" action ("GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER") when instantiating it with https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#GtkFileChooserAction

On startup, you could then set/restore the previously saved folder onto that widget so that it correctly indicates which folder the person has chosen.

**Comment by iacopodeenosee** [comment]
I like the "fat" selector widget :) , find it more convenient to directly select the folder that do open a file dialog and then return in the options window... I'll do some testing with filechooserbutton

**Comment by crquan** [comment]
No, the label above the file path chooser says `The file is saved in the path: /home/mint` and I changed a directory, the label reflected indeed to the new directory, but after I clicked another tab and click this tab `File Screencast` back, it shows default /home/mint again; although the file is generated at correct location if I start recording.

**Comment by iacopodeenosee** [comment]
better if you open a new issue for this bug, please in the issue add the log of this command:
```gnome-shell-extension-prefs EasyScreenCast@iacopodeenosee.gmail.com```
and the version of the extension or the version of gnome shell.
