### ISSUE TITLE
Unclear distinction between sections in the settings

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#28]
Settings currently have these sections:

* Options
* Recording area
* Screencast options
* "File screencast"
* GStreamer Pipeline

This is rather confusing, especially "Options" vs "Screencast options"

I would recommend something by areas of interest:
* User interface
  * Everything related to the shell's menu/notifications
  * Keyboard shortcuts
  * "Show a border around the area being recorded"
* Input & Performance
  * Audio input device
  * Framerate
  * Recording area
* Output (where and how to name the files)
* Advanced
 * Debug mode
 * GStreamer pipeline
 * Record cursor (could also go into the "Input" section, maybe)
 * Execute command after recording / "Command to execute after recording:" (could also go in the "Output" section, maybe)

And "Reset to defaults" is a global thing (AFAIK), so it should be taken out of the "User interface" tab and put below the whole notebook.

**Comment by iacopodeenosee** [comment]
https://github.com/iacopodeenosee/EasyScreenCast/commit/f91928035749debd6cab1fb1a94a25019e29e366
