### ISSUE TITLE
Simple quality slider setting

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#30]
When not using a custom gstreamer pipeline, it would be nice to have some sort of slider, from 0 to 100%, to easily set the "quality" of the recorded video, with 100% being nearly lossless (so you can post-process in video editing software etc.). It seems by default it uses min_quantizer=13 and max_quantizer=13, but I'm still able to see compression (so it's not the best quality for tutorial/demo material that needs to be edited afterwards) and pretty much nobody (among users, I mean) actually understands the notion of "quantizer" and how it functions...

**Comment by iacopodeenosee** [comment]
ok, need to redisign the UI preference for that, what parameters do you recommend to change to improve the quality of the recording? over the quantizer

**Comment by nekohayo** [comment]
That's the thing, I don't really know/understand the encoder's parameters :)

There's http://www.webmproject.org/docs/encoder-parameters/
and http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-vp8enc.html#GstVP8Enc--max-quantizer  but that one doesn't give any explanations, just the list of properties in vp8enc...

I'm not 110% sure but I think the quantizer boundary numbers are "lower = better quality". From the webm documentation page:

```
--min-q=<arg>                    (valid values 0-63, recommended value 0-4)
--max-q=<arg>                    (valid values --min-q to 63, recommended value 50-63)
```

> These two parameters define the range of quantizers that the rate control algorithm may use. A lower number equates to higher quality but more bits (note, however, that these are not real quantizer values just control values). In effect these two parameters can trump all the other rate control parameters. For example if you have set a maximum of 10 then the encoder will never use a quantizer greater than the value represented by 10, even if it massively overshoots the target bit rate. They are useful however, because they allow the user to set upper and lower quality limits for a clip.

**Comment by iacopodeenosee** [comment]
I'm no expert in gstreamer/codec too and hope someone more experienced to offer a little support :) for now after reading the documentation for me i can include in the GSP a combination of these keys, 

key | type | range value
------------ | ------------- | ------------- 
min-quantizer | gint | [0,63]
max-quantizer | gint | [0,63]
arnr-maxframes | gint(only for 2 pass-enc) | [0,15]
arnr-strength | gint(only for 2 pass-enc) | [0,6]
multipass-mode | GstVP8EncMultipassMode | [1,2]???
lag-in-frames | gint | [0,25]
noise-sensitivity | gint | [0,6]
cq-level | gint | [0,63]
end-usage | GstVP8EncEndUsage | [vbr, cbr, cq]
resize-allowed | gboolean | [true,false]
resize-down-threshold | gint | [0,100]
resize-down-threshold | gint | [0,100]
sharpness | gint | [0,7]
tuning | GstVP8EncTuning | [psnr, ssim]

i create 5 preset combination of these keys, and these can be invoke into a [gtkscale](https://developer.gnome.org/gtk3/unstable/GtkScale.html), from performance to lossless...
I'm still in the planning stage. 8y3

**Comment by crquan** [comment]
while for #47, can the quality option also resize the video? like on my `2880x1800` screen resolution it's HiDPi on a 15inch monitor actually, can there be an option to record at 1080p or 720p ? my use case is to make video tutorial and upload to youtube, if there can be a simple option to record at 1080p or 720p, and keep 1hr long video tutorial at reasonable file size (can it be < 500MB ?) then it would be awesome, and no need to other video postprocessing

**Comment by iacopodeenosee** [comment]
>  can there be an option to record at 1080p or 720p ? 

you can try to use this pipeline ```queue ! videorate ! queue ! videoscale ! video/x-raw, width=1920, height=1080 ! vp8enc min_quantizer=13 max_quantizer=13 cpu-used=5 deadline=1000000 threads=%T ! queue ! mux. pulsesrc ! queue ! audioconvert ! vorbisenc ! queue ! mux. webmmux name=mux```
I have not tested and I think that probably there will be a loss of quality, I suggest you to ask some gstreamer expert.

**Comment by iacopodeenosee** [comment]
https://github.com/iacopodeenosee/EasyScreenCast/commit/f91928035749debd6cab1fb1a94a25019e29e366
