### ISSUE TITLE
New release for 0.9.8?

### ISSUE THREAD

**Issue by sbrun** [iacopodeenosee/EasyScreenCast#31]
Hello
It would be great if you make a release for the new version 0.9.8, compatible with gnome shell 3.16
It's easier to manage in the distro with a release.

**Comment by iacopodeenosee** [comment]
hi, the 0.9.7 is compatible with GS 3.16.x, for now i just fix 2 minor bug(#19 #23) if you want i can create a intermediate release, like .0.9.7.1 for these; i'll release the 0.9.8 when redesign the interface preferences and maybe the integration of webcam.

**Comment by sbrun** [comment]
Hi,

An intermediate release like 0.9.7.1 is ok for me.
Thanks!

**Comment by iacopodeenosee** [comment]
done
http://github.com/iacopodeenosee/EasyScreenCast/releases/tag/0.9.7.1
