### ISSUE TITLE
Inject more variable in post command script

### ISSUE THREAD

**Issue by maboiteaspam** [iacopodeenosee/EasyScreenCast#32]
Hi,

It would be very convenient to inject more variables in the post script command like basename and dirname of the file.

**Comment by maboiteaspam** [comment]
would be great to pass a sort of desired quality options.

**Comment by iacopodeenosee** [comment]
hi, at the moment i replace the string only with the absolute path[AbsFilePath] of the screencast file, I could replace it with two variables:
- ScreenCastFileName
- AbsPathFolder
something like this?

for the "quality options" I have to rethink the interface preferences, i accept suggestions. thx

**Comment by maboiteaspam** [comment]
About the quality options, from my use, i wish i have web / desktop quality. My need is to produce gif from my videos later on (i can load that into github, cannot load real videos there).
Somthg like 1,2,3. Not a percent over a hundred, or something very precise. 
I think about an overall output settings, before i apply to it any kind of post treatment.

In regards of the post script command, yes that kind of values pre computed that end users can just use as he wishes.
I d say the names suggested are very long. I would prefer to have shorter names.
%fpath
%dirpath
%fname

We could also think about more variables like
%vlength (or video duration)
%vquality
%sX (this one is rather obscur, that would be X position on the screen : screenX)
%sY
%vwidth
%vheight

not quiet entirely totally sure of upcoming usages, i d say lets spray : ) Just clear i dont want it case sensitive, instead, pattern sensitive.

Some ideas, Hope that helps.

**Comment by iacopodeenosee** [comment]
for now I just added the variables for the file name and the folder that contains it, the percent character I replaced by underscores (_fpath, _dirpath, _fname).8y3
