### ISSUE TITLE
print screen mode

### ISSUE THREAD

**Issue by maboiteaspam** [iacopodeenosee/EasyScreenCast#36]
Hi,

How do you think about a print screen option in order to enjoy all the selection methods but to produce an unique png/jpeg file ?

Thanks !

**Comment by iacopodeenosee** [comment]
hi, what do you mean? something like a screenshoot? I think there is already the tool of gnome: gnome-screenshot and at the moment I'm working to improve the UI preferences and incorporate the webcam.
if interested in someone else can do it later ... but I think it is redundant. thx

**Comment by maboiteaspam** [comment]
oh, yes. sorry for that.

https://extensions.gnome.org/extension/61/area-screenshot/
https://extensions.gnome.org/extension/736/screenshot-window-sizer/
