### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#4]
I am very impressed by the feature set and reliability of EasyScreenCast. Excellent work!

The only thing missing to make it the be-all-end-all gnome-shell screencast recording tool would be to support recording audio at the same time.

The audio recording feature should also allow specifying a particular input device (in case the default is wrong - for example PulseAudio never remembers that I want to prioritize my USB microphone instead of the built-in analog audio).

**Comment by davelab6** [comment]
Not only sound but also the web cam, like silverbackapp.com

**Comment by iacopodeenosee** [comment]
you mean integrate a webcam video into videorecording? maybe in the right-bottom corner using gstreamer? if you want open a new issue. thx
