### ISSUE TITLE
Corrupt video recordings according with mpv

### ISSUE THREAD

**Issue by fturco** [iacopodeenosee/EasyScreenCast#43]
I'm trying EasyScreenCast 0.9.7.1-2 on GNOME 3.16.2. Most video recordings are corrupt according to the mpv video player:

```
$ mpv "Screencast_2015-09-28_14:24:00.webm"
Playing: Screencast_2015-09-28_14:24:00.webm
[mkv] Expected element 0x1043a770 not found
[mkv] Expected element 0x1254c367 not found
 (+) Video --vid=1 (*) 'Video' (vp9)
VO: [xv] 1280x800 yuv420p
V: 00:00:05 (75%)
[mkv] Corrupt file detected. Trying to resync starting from position 763471...
V: 00:00:05 (83%)
[mkv] Corrupt file detected. Trying to resync starting from position 769925...
V: 00:00:06 (98%)
[mkv] Corrupt file detected. Trying to resync starting from position 776695...
V: 00:00:06 (96%)


Exiting... (End of file)
```
It seems I can reproduce this problem only when randomly shaking windows on screen and relying on special effects from GNOME. If I record an idle screen the resulting file is not corrupt. My computer is a laptop from 2008, so perhaps it is simply not fast enough. I didn't change the default gstreamer pipeline but perhaps there are some options I can use to allow my computer record screencasts. Frankly I don't even think this is a problem with EasyScreenCast only, because I obtain corrupt videos with the default GNOME recording application, too.

**Comment by iacopodeenosee** [comment]
hi, I have a laptop ancient too :) and  I think this issue is dependent on the hardware poorly performing but also by not optimizing code of the recorder integrated into gnome-shell(ESC is only a graphical interface of it); the best way is to open a report on bugzilla in the gnome-shell section.
thx

**Comment by fturco** [comment]
Done as suggested: https://bugzilla.gnome.org/show_bug.cgi?id=755802.
