### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [iacopodeenosee/EasyScreenCast#44]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by iacopodeenosee** [comment]
hi, i can't test ESC in GS 3.18 because i'm still with 3.16 version, if you want to test it for me you just change the file metadata.json, change the value of the params "shell-version" into "3.18"; if everything works after restarting the shell then i update the extension on the GSE site.
thx

**Comment by kparal** [comment]
I disabled [extension version validation](http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/) and installed this extension per instructions in readme. After restarting gnome-shell, I see it marked as "error". In the log, I see:
```
Sep 30 09:17:40 dryad gnome-session[1763]: Gjs-Message: JS LOG: Extension "EasyScreenCast@iacopodeenosee.gmail.com" had error: TypeError: this.smAreaRec.status is undefined
```

**Comment by iacopodeenosee** [comment]
they eliminated the right label of the submenu that I used to show the choices of the user, now I have to redesign part of the interface. be patient :)
Ref: https://git.gnome.org/browse/gnome-shell/commit/js/ui/popupMenu.js?id=fa0e54edbb584624c9e85b6a8356b71e01c1baec

**Comment by kparal** [comment]
Should the commit close this issue? It does not edit the metadata and new version is not yet available at extensions.gnome.org. Should I file a different ticket?

**Comment by iacopodeenosee** [comment]
this commit https://github.com/iacopodeenosee/EasyScreenCast/commit/192c770c37d32c2e21949b044623c9d0bcb860ab update the metadata file, if you can test this version on GS 3.18 i upload it into GSE site, thx

**Comment by kparal** [comment]
I have tested it and it seems to be working well. Please upload, thank you!
