### ISSUE TITLE
when you change the size of the video

### ISSUE THREAD

**Issue by ivanchenkoandriy** [iacopodeenosee/EasyScreenCast#45]
https://drive.google.com/open?id=0B0pntHqExC0fWDFPSFhtdGV4R0E

**Comment by iacopodeenosee** [comment]
hi, I think the problem is in the recorder integrated into gnome-shell(ESC is only a graphical interface of it); the best way to resolve is to open a report on bugzilla in the gnome-shell section:
https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-shell
thx
