### ISSUE TITLE
ISSUE: Gjs-Message: JS LOG: Extension "EasyScreenCast@iacopodeenosee.gmail.com" had error: Error: Wrong type undefined; string expected

### ISSUE THREAD

**Issue by pszafer** [iacopodeenosee/EasyScreenCast#50]
Hello,

First thanks for great extension!
For some time I cannot install your extension, everytime I did upgrade in extensions.gnome.org I had to revert to previous version :/

This time, I decided to find problem. I'm not gnome dev so sorry if I write something 'stupid'...

So error:
```
Gjs-Message: JS LOG: Extension "EasyScreenCast@iacopodeenosee.gmail.com" had error: Error: Wrong type undefined; string expected
```

So after few testing, I've got something I think is a bug
> File: extensions.js, line 176
```
    _addSubMenuAreaRec: function () {
        this.smAreaRec = new PopupMenu.PopupSubMenuMenuItem('', true);
        this.smAreaRec.icon.icon_name = 'view-fullscreen-symbolic';
        var arrMI = this._createMIAreaRec();
        for (var ele in arrMI) {
            this.smAreaRec.menu.addMenuItem(arrMI[ele]);
        }
        this.smAreaRec.label.text =
            this.AreaType[Pref.getOption('i', Pref.AREA_SCREEN_SETTING_KEY)];
        this.menu.addMenuItem(this.smAreaRec);
    },
```

This line:
```
 this.smAreaRec.label.text =
            this.AreaType[Pref.getOption('i', Pref.AREA_SCREEN_SETTING_KEY)];
```

I know that if type is 'i' you want integer, if 's' you want string.
label.text should be string, but if I just change for 's' it returning me null var.

For now I just changed it for simple string and it is working for me.

I wrote new topic, but I thinks it is duplicated of https://github.com/iacopodeenosee/EasyScreenCast/issues/41

**Comment by iacopodeenosee** [comment]
hi, i presume you have installed the latest version (0.9.7.3) from git release, if not please download it and give it a try; in the section of code you reported there are not errors, i get the element of the string array **AreaType** by the integer stored into the preference; i can't reproduce your situation, please show all the relative log. thx
*however i think this is not bound with issue #41 because this problem was present before this piece of code*

**Comment by pszafer** [comment]
in metadata.json there is version 0.9.8.

Only error I've got is:
```
Gjs-Message: JS LOG: Extension "EasyScreenCast@iacopodeenosee.gmail.com" had error: Error: Wrong type undefined; string expected
```

When I print this:
```
global.log(Pref.getOption('i', Pref.AREA_SCREEN_SETTING_KEY));
```
It gives me integer 4.
Hmmm, more info:
I have Arch Linux, Gnome 3.18.3

I can replicate this bug on all my gnome computers (all three).

In file ```org.gnome.shell.extensions.easyscreencast.gschema.xml``` shouldn't it be:
```xml
        <key name="area-screen" type="i">
            <default>0</default>
            <summary>select area of screencast</summary>
            <description>select area of screencast</description>
        </key>
```

type='s' instead of 'i'?

**Comment by iacopodeenosee** [comment]
> in the section of code you reported there are not errors, i get the element of the string array AreaType by the integer stored into the preference

**area-screen** must be a integer, i use this index to extract the right string from array **AreaType**; the code is simly this
``` var i=0; var str=''; 
i=Pref.getOption('i', Pref.AREA_SCREEN_SETTING_KEY); 
str=this.AreaType[i]; this.smAreaRec.label.text = str;```
i think is clear how it works and the value **4** you resulted is nonsense the value must be between **0 and 3**; try to delete the file where are the stored preference and recompile it, something like this:
1 -> ```rm ~/.local/share/gnome-shell/extensions/EasyScreenCast\@iacopodeenosee.gmail.com/schemas/gschemas.compiled```
2 -> ```glib-compile-schemas ~/.local/share/gnome-shell/extensions/EasyScreenCast\@iacopodeenosee.gmail.com/schemas```
3 -> ```restart gnome shell and try the extension```
please enable **Enable verbose debug** into the option window, then send here all the complete log, otherwise i can not help you. thx

**Comment by pszafer** [comment]
ok, it is working after 1 and 2 steps.
So for now I'm ok, but I can try revert gschemas.compiles (I moved it not deleted) and enable verbose debug. Maybe this will help you somehow

**Comment by iacopodeenosee** [comment]
it would be interesting to understand how the value **area-screen** get to 4, but i think the log now is useless; the gschema.compiled available from git repo set the value to **2** (record a selected window) for my mistake, the next update I'll fix this problem setting it to **0** (record all desktop).
I also implemented the ability to reset this value from the button __Restore default options__  on the UI window options -> https://github.com/iacopodeenosee/EasyScreenCast/commit/41574d83ee9b2c6ca55a455477ecf5e6dba1f8bd
