### ISSUE TITLE
maximum duration does not work on GNOME 3.14

### ISSUE THREAD

**Issue by kparal** [iacopodeenosee/EasyScreenCast#6]
I set `Maximum duration screencast` to 10 seconds, but EasyScreenCast continued to record even after 10 seconds (I waited about half a minute, then manually ended it). It seems that that option has no effect.

**Comment by iacopodeenosee** [comment]
I believe that only in version 3.10.1 was this option enabled, in later versions must be eliminated.
I check the source of GS to be sure, here the bug related: https://bugzilla.gnome.org/show_bug.cgi?id=708660
