### ISSUE TITLE
Doesn't start recording when I click "Start Recording"

### ISSUE THREAD

**Issue by hydbird** [iacopodeenosee/EasyScreenCast#66]
It only records when I select the option Quality > Custom GStreamer Pipeline. Is there a way to troubleshoot this? Im using Arch Linux with Gnome 3.18.2

**Comment by iacopodeenosee** [comment]
> Is there a way to troubleshoot this?

which version do you use? latest from git repo or from gnome extension site? 
you could try to restore the default options from the extension setting window, however if you still have problems you must enable the verbose logs in options window and after that you can find the logs by typing this on terminal -> `journalctl --since=today --no-pager | grep js`
paste here the result, thx

**Comment by hydbird** [comment]
I'm using the one from gnome extension site. I've tried restoring the defaults but no luck. When I use `grep js` I get too many lines including the logs for the javascripts in the Firefox. Is there a way to narrow it more?

**Comment by hydbird** [comment]
Anyway new day new logs :) here's the output of `journalctl --since=today --no-pager | grep js`
[recorder.txt](https://github.com/iacopodeenosee/EasyScreenCast/files/200356/recorder.txt)

**Comment by iacopodeenosee** [comment]
> Gjs-Message: JS LOG: ESC>-§-get option||devW: 0||devA: -1||Qgsp: 1||Qwc: ||Res: 0||Cont: 3

the **initial value** of the audio device was set to -1, so it was going out of the array of audio devices, this bug manifested itself only if you start recoding without ever having set before any audio device from the indicator menu; if you want to test it, you can download the latest release from the github repo or wait for the publication of the update on the gnome extension site.

**Comment by hydbird** [comment]
You are right. When I chose the "Default Audio Source" as audio source, it worked. It's usable in this way right now. I prefer to use the gnome extension site version if my instance will be updated.
