### ISSUE TITLE
Application not working in gnome-shell 3.20

### ISSUE THREAD

**Issue by dreamer1234** [iacopodeenosee/EasyScreenCast#69]
Hello: 

The application does not seem to work since I have updated to gnome-shell 3.20. Everything is working fine but the easyscreencast application. My distribution is arch linux. 
I've cloned the git repo but it doesn't work either. When I try to record, it says "recording error" . 
Where is the log of the application so I can send it to you?

Thanks

**Comment by iacopodeenosee** [comment]
> Where is the log of the application so I can send it to you?

hi, you must enable the verbose logs in options window and after that you can find the logs by typing this on terminal -> journalctl --since=today --no-pager | grep js
paste here the result, thx

**Comment by dreamer1234** [comment]
Hello:

This is the log. Thanks a lot for 

abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-intercept key combination
abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-start recording
abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-type of selection of the area to record: 2
abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-window selection init
abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-capture selection init
abr 08 15:33:57 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-refresh indicator -A false -F undefined
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-capture selection stop
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-windows pre wx: -1 wy: 26 height: 743  width: 1368
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-windows post wx: -1 wy: 26 height: 742 width: 1367
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-£-selection x:-1 y:26 height:742 width:1367
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-instant recording called
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-&-start video recording
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-get file extension C-> 0
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-COMPOSE GSP
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-#-mixer _init
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f7547f95070 native@0x2fe6f70] state -> 1
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-get option||devW: 0||devA: 1||Qgsp: 1||Qwc: ||Res: 0||Cont: 0
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-SCREEN-AUDIO(d)
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-replace audio default->true
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-pipeline pre-audio:queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! _SCREENCAST_RES_ _ENCODER_VIDEO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc ! audioconvert ! _ENCODER_AUDIO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. _CONTAINER_ name=mux  aq:vorbisenc
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-pipeline post-audio:queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! _SCREENCAST_RES_ _ENCODER_VIDEO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. _CONTAINER_ name=mux
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-§-final GSP :queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 !  vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. webmmux name=mux
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-&-path/file template : /home/xxxxx/Documentos/Screencast_%d_%t.webm.webm
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-&-ERROR(screencast execute) - GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-&-stop video recording
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-record ERROR
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-*-refresh indicator -A false -F undefined
abr 08 15:33:58 darkstar org.gnome.Shell.desktop[708]: Gjs-Message: JS LOG: ESC>-&-screencast stop - true

**Comment by iacopodeenosee** [comment]
> Gjs-Message: JS LOG: ESC>-£-windows pre wx: -1 wy: 26 height: 743 width: 1368
> ....
>Gjs-Message: JS LOG: ESC>-&-ERROR(screencast execute) - GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params

i think the problem is the position of the window you selected, the window must be into the screen area:
**wx >=0**
you can solve by moving the window into the screen area or change the type of selection, try **Record a selected area**.

**Comment by dreamer1234** [comment]
Hello:
It does seem to work selecting an area but not recording a window. But this is a very nice workaround for me :). 
I was opening the issue because your extension is very important for me because I can record the videos of my University to watch them offline at my travellings by train. 

 Thanks a lot for the help and for making such an interesting thing.

**Comment by iacopodeenosee** [comment]
When I upgrade to GS 3.20 I'll do some tests to figure out the problem. thx

**Comment by varemenos** [comment]
Shouldn't this be left open until it's actually resolved?
I've been searching the open issues for a 3.20 compatibility issue and couldn't find it until I've broaden the search to include the closed issues...

**Comment by iacopodeenosee** [comment]
the title of the issue is misleading, simply can not record a window if this is **not entirely** on the screen, I'll try to improve the explanation of the error in future versions, however, this issue has been resolved, if you have incompatibilities with version 3.20 open a new issue. thx
