### ISSUE TITLE
mouse not working on gnome shell widgets inside the area marked with "show area screencast during recording"

### ISSUE THREAD

**Issue by kparal** [iacopodeenosee/EasyScreenCast#7]
If I enable *show area screencast during recording* option and then record either the full screen or some specific part of the screen, I can't use the mouse click anywhere inside the marked area *on gnome-shell widgets*. That includes the top bar (if it is inside the marked area), anything in the gnome-shell overview, or the notification bar.

For example, I can't click on anything inside the red rectangle in gnome-shell overview in the following image:
![area](https://cloud.githubusercontent.com/assets/755451/5627682/1a221a3c-959c-11e4-975f-eaf968145e46.png)

If I disable "show area screencast during recording", the mouse clicks operate normally.

GNOME 3.14

**Comment by windandflame** [comment]
I can confirm that this is a bug as well.  Running Debian Jessie, Linux 3.16, Gnome 3.14.
