### ISSUE TITLE
I'm unable to record, it returns an error every time!

### ISSUE THREAD

**Issue by Dumbledorf** [iacopodeenosee/EasyScreenCast#74]
I get an error telling me to look in the log files. This is what the log files say:

> May 01 22:12:47 User org.gnome.Shell.desktop[10030]: EasyScreenCast_Indicator<.destroy@/home/user/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:662
> May 01 22:12:47 User org.gnome.Shell.desktop[10030]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
> May 01 22:12:47 User org.gnome.Shell.desktop[10030]: disable@/home/user/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:736

**Comment by iacopodeenosee** [comment]
hi, i need more info, can you enabble the **verbose log** into option window and after that paste here **all** the result of the log? see here :
https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs
thx

**Comment by Dumbledorf** [comment]
I found out that I didn't need any screen capture software anyway, so I uninstalled it.
