### ISSUE TITLE
Default to VP8 and offer VP9 encoding as an option

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#75]
I noticed that the newest version now allows setting the container format... would be nice if one could specify that the codec should be VP8 instead of VP9, as most (if not all) computers are unable to handle real-time VP9 encoding at HD resolutions, resulting in gnome-shell quickly eating the entire RAM and crashing the system...

**Comment by iacopodeenosee** [comment]
the default video encoder for webm container is **VP8** for the same problems you listed, I can add a new element in the list of container with VP9 encoder, something like this:

- Webm VP8
- Webm VP9
- Mp4
- Mkv
- Ogg

although I believe that if one serves VP9 can always create a custom pipeline.

**Comment by nekohayo** [comment]
Oooh, I thought VP9 was still the default, seems like I can toggle off my "custom" gstreamer pipeline now, at last ;)
