### ISSUE TITLE
screencast of a specific window fails

### ISSUE THREAD

**Issue by cmurf** [iacopodeenosee/EasyScreenCast#77]
When I set "Record a selected window" then choose record, I'm prompted to select a window. The instant I click anywhere, I get an error notification:ERROR RECORDER - see logs.  In the logs I see:

`May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: (gnome-shell:1855): Clutter-CRITICAL **: clutter_paint_volume_set_height: assertion 'height >= 0.0f' failed
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-capture selection stop
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-windows pre wx: 1258 wy: 1240 height: 989  width: 1368
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-windows post wx: 1258 wy: 1240 height: -190 width: 422
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-selection x:1258 y:1240 height:-190 width:422
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-*-instant recording called
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-&-start video recording
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-§-get file extension C-> 0
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-§-COMPOSE GSP
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-#-mixer _init
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f4c304382e0 native@0x55a65174f530] state -> 1
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-§-get option||devW: 0||devA: 0||Qgsp: 0||Qwc: ||Res: 0||Cont: 0
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-§-SCREEN
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-§-final GSP : vp8enc min_quantizer=13 max_quantizer=20 cpu-used=5 deadline=1000000 sharpness=2 target-bitrate=10000 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! webmmux
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-&-path/file template : /home/chris/Videos/Screencast_%d_%t.webm.webm
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-&-ERROR(screencast execute) - GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-&-stop video recording
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-*-record ERROR
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-*-refresh indicator -A false -F undefined
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: ** (gnome-shell:1855): CRITICAL **: shell_recorder_close: assertion 'recorder->state != RECORDER_STATE_CLOSED' failed
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-&-screencast stop - true
`

If I change to Record a selected monitor, that appears to work.

**Comment by cmurf** [comment]
Ok that's incredibly ugly and I have no idea how to fix it, so here's the same info better formatted.
https://paste.fedoraproject.org/364028/

gnome-shell-3.18.5-1.fc23.x86_64
clutter-1.24.2-1.fc23.x86_64

**Comment by iacopodeenosee** [comment]
This occurs when you select a window that is partially off the screen (like #69 ):
...post wx: 1258 wy: 1240 **height: -190** width: 422...
```
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-windows pre wx: 1258 wy: 1240 height: 989  width: 1368
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-windows post wx: 1258 wy: 1240 height: -190 width: 422
May 08 10:35:46 f23m.localdomain gnome-shell.desktop[1855]: Gjs-Message: JS LOG: ESC>-£-selection x:1258 y:1240 height:-190 width:422
```
 you can solve by moving the window into the screen area or change the type of selection, try **Record a selected area**. if you need more support open a new issue.  thx
