### ISSUE TITLE
Error: No property show_all on this GObject GstDeviceMonitor

### ISSUE THREAD

**Issue by pbwolf** [iacopodeenosee/EasyScreenCast#78]
In Firefox 45, Gnome 3.16.4, I hit the button to install EasyScreenCast and affirmed a subsequent Firefox inquiry, and a red Error mark appeared in place of the install button.  Then I followed instructions and pressed Alt+F2, issued the r command, reloaded the installation page, and once more chose to install it. This time the red Error mark reappeared, with a tools button to the left.  I pressed the tools button and got the following note:

```
Error: No property show_all on this GObject GstDeviceMonitor

Stack trace:
  HelperWebcam<._init@/home/pbwolf/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilwebcam.js:38
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
  EasyScreenCastSettingsWidget<._init@/home/pbwolf/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  buildPrefsWidget@/home/pbwolf/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:730
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1
```

**Comment by iacopodeenosee** [comment]
hi, in gnome-shell 3.16 this extension has a problem in obtaining the webcam devices, known problem that I have not solved yet (see #67 ), there is a workaround: 

- comment the line **110** in extensions.js file
- comment the line **38** in utilwebcam.js file

continue here -> #80
