### ISSUE TITLE
Audio recording doesn't work.

### ISSUE THREAD

**Issue by JuniorBee** [iacopodeenosee/EasyScreenCast#79]
In hp 635 laptop all of options for audio sources does not work properly.

**Comment by iacopodeenosee** [comment]
hi, i need more info to help you, like:

- a detailed description of the problem
- gnome-shell version
- distro in use
- where you get this extension [repo distro, gnomeshellextension web site, git repo]
- the logs of the extension -> https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs
