### ISSUE TITLE
ERROR RECORDER - See logs for more info

### ISSUE THREAD

**Issue by xBioClown** [iacopodeenosee/EasyScreenCast#83]
Hello there,
Actualy i've installed ubuntu 15.04 with unity then upgadred my dist to 15.10, on realeased i've upgraded to 16.04 and installes GNOME Shell, then installed EasyScreenCast, configured that to record with mp4 container and extension file to .mp4.

So every time i tried to record the only thing it do is show me
ERROR RECORDER - See logs for more info.
Once and once.
All updates and apps are the last released.

Please HELP!!!

**Comment by iacopodeenosee** [comment]
hi, if you get a error only with mp4/x264 codec i fixed this problem in the last release, i'm waiting the review of the gnome shell extension site to publish it, meantime you can try the [last release from github repo](https://github.com/iacopodeenosee/EasyScreenCast/archive/0.9.8.4.zip). anyway for better support please **[add the log of the extension](https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs)**. thx

**Comment by xBioClown** [comment]
hi, man thx i've already updated files and its working now.
