### ISSUE TITLE
File settings, duplicated file extension in file name and different destination folder

### ISSUE THREAD

**Issue by jjnilton** [iacopodeenosee/EasyScreenCast#85]
File name shows with extension ".webm.webm", removing the ".webm" from the filename template on File settings make it worked as expected.
 
And destination folder shows $HOME, but the videos are saved in "$HOME/Videos" folder by default.

**Comment by iacopodeenosee** [comment]
> File name shows with extension ".webm.webm", removing the ".webm" from the filename template on File settings make it worked as expected.

fixed at https://github.com/iacopodeenosee/EasyScreenCast/commit/cf0c87efcdab990363c76c8bde76dca3cdcef5cf

> And destination folder shows $HOME, but the videos are saved in "$HOME/Videos" folder by default.

if **$XDG_VIDEOS_DIR** is setup the file will be saved in it, otherwise it will be saved in the home, What do you suggest? an update of the widget in the initial state? thx

**Comment by jjnilton** [comment]
Thanks!

I think an update in the initial state would work.

It could show the Videos instead of $HOME if $XDG_VIDEOS_DIR is setup, because now it shows $HOME but saves to Videos dir, so when I first installed I went to $HOME to find the video files and they weren't there.
