### ISSUE TITLE
Error at record time !

### ISSUE THREAD

**Issue by mcgivrer** [iacopodeenosee/EasyScreenCast#87]
While trying to record as a "window" , i got the following error:

ureadahead:/home/frederic/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/metadata.json: Error retrieving chunk extents: Opération non supportée

"Opération non supportée" => Not supported operation

**Comment by iacopodeenosee** [comment]
hi, i need more info:
- can you enable the **verbose log** into option window and after that paste here all the result of the log? see here :
https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs
- which version of gnome-shell you use?
- ESC crash only with **window selection**?

thx
