### ISSUE TITLE
ERROR WHEN SELECTING AUDIO SOURCE

### ISSUE THREAD

**Issue by alec9** [iacopodeenosee/EasyScreenCast#94]
I guess is not a complicate issue but I just don't feel like troubleshooting today. So as the tittle says, when I select my audio device for recording my screen, the recording application wont allow me to record, what it does is pops a message "ERROR RECORDER - see logs for more info" regardless what I chose as audio source: default or Built-in. The recorder works perfectly fine when I select no audio source. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Logs

 * Log, enable verbose debug logs into options window, and after that try  `journalctl --since=today --no-pager | grep js`
 * webcam info: `v4l2-ctl --all`
 * webcam info: `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info: `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`
## Your Environment

* where you downloaded the extension?
 [ ] Gnome shell extension website
 [ ] Last release from git repo
 [ ] Last version from git on master branch repo
* gnome shell version:

* Operating System and version:

**Comment by iacopodeenosee** [comment]
hi, i need more info and the log of the extension to understand what went wrong. see [here](https://github.com/iacopodeenosee/EasyScreenCast#how-to-view-the-logs). thx

**Comment by alec9** [comment]
is the jack
